# Generated by Django 3.2.16 on 2022-11-02 13:41

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlaceCoord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(db_index=True, max_length=255, unique=True, verbose_name='адрес')),
                ('lng', models.DecimalField(decimal_places=6, max_digits=9, validators=[django.core.validators.MinValueValidator(limit_value=-180), django.core.validators.MaxValueValidator(limit_value=180)])),
                ('lat', models.DecimalField(decimal_places=6, max_digits=8, validators=[django.core.validators.MinValueValidator(limit_value=-90), django.core.validators.MaxValueValidator(limit_value=90)])),
                ('request_time', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='время запроса')),
            ],
        ),
    ]
