# Generated by Django 3.2.16 on 2022-11-03 14:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calcdistances', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='placecoord',
            name='hash',
            field=models.PositiveIntegerField(db_index=True, default=0, unique=True, validators=[django.core.validators.MaxValueValidator(limit_value=9999999999)]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='placecoord',
            name='address',
            field=models.CharField(max_length=255, verbose_name='адрес'),
        ),
    ]
