# Generated by Django 3.2.16 on 2022-11-10 16:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('calcdistances', '0002_auto_20221103_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placecoord',
            name='request_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='время запроса'),
        ),
    ]
