# Generated by Django 3.2.16 on 2022-11-10 19:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calcdistances', '0003_alter_placecoord_request_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placecoord',
            name='lat',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(limit_value=-90), django.core.validators.MaxValueValidator(limit_value=90)]),
        ),
        migrations.AlterField(
            model_name='placecoord',
            name='lng',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(limit_value=-180), django.core.validators.MaxValueValidator(limit_value=180)]),
        ),
    ]
