# Generated by Django 3.2.16 on 2022-11-10 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calcdistances', '0005_rename_request_time_placecoord_request_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placecoord',
            name='address',
            field=models.CharField(max_length=255, unique=True, verbose_name='адрес'),
        ),
    ]
