# Generated by Django 3.2.16 on 2022-12-02 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calcdistances', '0006_alter_placecoord_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placecoord',
            name='address',
            field=models.CharField(max_length=255, verbose_name='адрес'),
        ),
        migrations.AlterField(
            model_name='placecoord',
            name='hash',
            field=models.PositiveIntegerField(db_index=True, unique=True),
        ),
    ]
