# Generated by Django 3.2.16 on 2022-12-02 14:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calcdistances', '0007_auto_20221202_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placecoord',
            name='hash',
            field=models.PositiveIntegerField(db_index=True, unique=True, validators=[django.core.validators.MaxValueValidator(limit_value=9999999999)]),
        ),
    ]
