# Generated by Django 3.2.16 on 2022-12-02 15:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calcdistances', '0008_alter_placecoord_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placecoord',
            name='hash',
            field=models.BigIntegerField(db_index=True, unique=True, validators=[django.core.validators.MinValueValidator(limit_value=1)]),
        ),
    ]
