# Generated by Django 3.2.16 on 2022-12-17 04:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calcdistances', '0010_alter_placecoord_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placecoord',
            name='hash',
            field=models.PositiveBigIntegerField(db_index=True, unique=True, validators=[django.core.validators.MaxValueValidator(limit_value=9999999999)]),
        ),
    ]
