# Generated by Django 3.2.16 on 2022-10-29 03:17

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0038_auto_20221025_1435'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderposition',
            options={'ordering': ['order', 'product'], 'verbose_name': 'пункт позиции заказа', 'verbose_name_plural': 'позиции заказа'},
        ),
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.CharField(max_length=255, verbose_name='адрес доставки'),
        ),
        migrations.AlterField(
            model_name='order',
            name='phonenumber',
            field=phonenumber_field.modelfields.PhoneNumberField(db_index=True, max_length=128, region=None, verbose_name='мобильный телефон'),
        ),
    ]
