# Generated by Django 3.2.16 on 2022-10-30 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0041_auto_20221029_0749'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-updated_at', 'address'], 'verbose_name': 'заказ', 'verbose_name_plural': 'заказы'},
        ),
        migrations.AddField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('UN', 'Необработанный'), ('RS', 'Передан в ресторан'), ('CR', 'Передан курьеру'), ('OK', 'Выполнен')], db_index=True, default='UN', max_length=2),
        ),
    ]
