# Generated by Django 3.2.16 on 2022-10-30 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0042_auto_20221030_0856'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_status',
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('UN', 'Необработанный'), ('RS', 'Передан в ресторан'), ('CR', 'Передан курьеру'), ('OK', 'Выполнен')], db_index=True, default='UN', max_length=2, verbose_name='статус'),
        ),
    ]
