# Generated by Django 3.2.16 on 2022-10-30 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0045_alter_order_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-registrated_at', 'address'], 'verbose_name': 'заказ', 'verbose_name_plural': 'заказы'},
        ),
        migrations.RenameField(
            model_name='order',
            old_name='updated_at',
            new_name='called_at',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='created_at',
            new_name='registrated_at',
        ),
    ]
