# Generated by Django 3.2.16 on 2022-10-30 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0048_auto_20221030_1013'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('CH', 'Наличностью'), ('RM', 'Электронно')], db_index=True, default='CH', max_length=2, verbose_name='способ оплаты'),
            preserve_default=False,
        ),
    ]
