# Generated by Django 3.2.16 on 2022-10-30 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0049_order_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('CH', 'Наличностью'), ('RM', 'Электронно')], db_index=True, default='CH', max_length=2, verbose_name='способ оплаты'),
        ),
    ]
