# Generated by Django 3.2.16 on 2022-11-10 16:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0052_auto_20221102_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderposition',
            name='quantity',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='количество'),
        ),
    ]
