# Generated by Django 3.2.16 on 2022-11-12 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calcdistances', '0006_alter_placecoord_address'),
        ('foodcartapp', '0054_alter_order_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='calcdistances.placecoord'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='restaurants', to='calcdistances.placecoord'),
        ),
    ]
